root : cgh-root.cu
	nvcc -lcuda -lcudart cgh-root.cu -o cgh-root.out
float : cgh-float.cu
	nvcc -lcuda -lcudart cgh-float.cu -o cgh-float.out
double : cgh-double.cu
	nvcc -lcuda -lcudart cgh-double.cu -o cgh-double.out
