root : cgh-root.c
	gcc cgh-root.c -lm -o cgh-root.out
kai : cgh-root-kai.c
	gcc cgh-root-kai.c -lm -o cgh-root-kai.out
kaif : cgh-root-kai.c
	gcc cgh-root-kai.c -O1 -lm -o cgh-root-kai-fast.out
fresnel : cgh-fresnel.c
	gcc cgh-fresnel.c -lm -o cgh-fresnel.out
