root : cgh-root.c
	gcc cgh-root.c -lm -O3 -o cgh-root.out
kai : cgh-root-kai.c
	gcc cgh-root-kai.c -lm -O3 -o cgh-root-kai.out
fresnel 9: cgh-fresnel.c
	gcc cgh-fresnel.c -lm -O3 -o cgh-fresnel.out
float : cgh-float.c
	gcc cgh-float.c -lm -O3 -o cgh-float.out
double : cgh-double.c
	gcc cgh-double.c -lm -O3 -o cgh-double.out
floatf : cgh-float-fresnel.c
	gcc cgh-float-fresnel.c -lm -O3 -o cgh-float-fresnel.out
doublef : cgh-double-fresnel.c
	gcc cgh-double-fresnel.c -lm -O3 -o cgh-double-fresnel.out
sinpuku : cgh-sinpuku.c
	gcc cgh-sinpuku.c -lm -O3 -o cgh-sinpuku.out
isou : cgh-isou.c
	gcc cgh-isou.c -lm -O3 -o cgh-isou.out
