fresnel : cgh-fresnel-full.cu
	nvcc -lcuda -lcudart cgh-fresnel-full.cu -o cgh-fresnel-full.out
float : cgh-float.cu
	nvcc -lcuda -lcudart cgh-float.cu -o cgh-float.out
double : cgh-double.cu
	nvcc -lcuda -lcudart cgh-double.cu -o cgh-double.out
