fresnel : cgh-fresnel.cu
	nvcc -lcuda -lcudart cgh-fresnel.cu -o cgh-fresnel.out
float : cgh-float.cu
	nvcc -lcuda -lcudart cgh-float.cu -o cgh-float.out
double : cgh-double.cu
	nvcc -lcuda -lcudart cgh-double.cu -o cgh-double.out
